---
site_name: "L_lib.sh"
site_url: "https://kamilcuk.github.io/L_lib.sh"
repo_url: "https://github.com/kamilcuk/L_lib.sh"
repo_name: "kamilcuk/L_lib.sh"
watch: [mkdocs.yml, README.md, bin]
copyright: Copyright &copy; 2025 Kamil Cukrowski
edit_uri: edit/main/docs/

nav:
  - Overview:
      - Index: index.md
      - Bash expansions: expansions.md
      - Bugs: bugs.md
  - Documentation:
      - globals: section/globals.md
      - colors: section/colors.md
      - ansi: section/ansi.md
      - has: section/has.md
      - stdlib: section/stdlib.md
      - exit_to: section/exit_to.md
      - path: section/path.md
      - string: section/string.md
      - array: section/array.md
      - args: section/args.md
      - utilities: section/utilities.md
      - log: section/log.md
      - sort: section/sort.md
      - trap: section/trap.md
      - unittest: section/unittest.md
      - map: section/map.md
      - asa: section/asa.md
      - argparse: section/argparse.md
      - proc: section/proc.md
      - lib: section/lib.md
      - all: section/all.md

theme:
  name: material
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.instant.preview
  - navigation.path
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference

markdown_extensions:
- attr_list
- admonition
# - callouts
- footnotes
- pymdownx.blocks.admonition
- pymdownx.blocks.tab:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.magiclink
- pymdownx.snippets:
    base_path: [!relative $config_dir]
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
- pymdownx.tasklist:
    custom_checkbox: true
- toc:
    permalink: true


plugins:
- search
- autorefs
# - markdown-exec
- section-index
- mkdocstrings:
    default_handler: sh
    handlers:
      sh:
        options:
          includeregex: "^L_.*"
          excluderegex: "^_L_.*$"
          source_url: "https://github.com/Kamilcuk/L_lib/blob/main/{file}#L{line}"

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/kamilcuk
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: Let us know how we can improve this page.
