_L_test_version() {
	local -a line27
	L_readarray -n 1 -s 26 -t line27 <"$L_LIB_SCRIPT"
	line27=${line27%$'\r'}
	L_unittest_eq "$line27" "L_LIB_VERSION=$L_LIB_VERSION"

	L_unittest_checkexit 0 L_version_cmp "0" eq "0"
	L_unittest_checkexit 0 L_version_cmp "0" '==' "0"
	L_unittest_checkexit 1 L_version_cmp "0" '!=' "0"
	L_unittest_checkexit 0 L_version_cmp "0" '<' "1"
	L_unittest_checkexit 0 L_version_cmp "0" '<=' "1"
	L_unittest_checkexit 0 L_version_cmp "0.1" '<' "0.2"
	L_unittest_checkexit 0 L_version_cmp "2.3.1" '<' "10.1.2"
	L_unittest_checkexit 0 L_version_cmp "1.3.a4" '<' "10.1.2"
	L_unittest_checkexit 0 L_version_cmp "0.0.1" '<' "0.0.2"
	L_unittest_checkexit 0 L_version_cmp "0.1.0" gt "0.0.2"
	L_unittest_checkexit 0 L_version_cmp "$BASH_VERSION" gt "0.1.0"
	L_unittest_checkexit 0 L_version_cmp "1.0.3" "<" "1.0.7"
	L_unittest_checkexit 1 L_version_cmp "1.0.3" ">" "1.0.7"
	L_unittest_checkexit 0 L_version_cmp "2.0.1" ">=" "2"
	L_unittest_checkexit 0 L_version_cmp "2.1" ">=" "2"
	L_unittest_checkexit 0 L_version_cmp "2.0.0" ">=" "2"
	L_unittest_checkexit 0 L_version_cmp "1.4.5" "~=" "1.4.5"
	L_unittest_checkexit 0 L_version_cmp "1.4.6" "~=" "1.4.5"
	L_unittest_checkexit 1 L_version_cmp "1.5.0" "~=" "1.4.5"
	L_unittest_checkexit 1 L_version_cmp "1.3.0" "~=" "1.4.5"
	#
	L_unittest_checkexit 1 L_version_cmp "1.1.post1" "==" "1.1"
	L_unittest_checkexit 1 L_version_cmp "1.1.post1" "==" "1.1.*"
	L_unittest_checkexit 0 L_version_cmp "1.1.post1" "==" "1.1.post1"
	L_unittest_checkexit 0 L_version_cmp "1.1" "==" "1.1"
	L_unittest_checkexit 0 L_version_cmp "1.1" "<" "1.1.0"
	L_unittest_checkexit 1 L_version_cmp "1.1" "==" "1.1.dev1"
	L_unittest_checkexit 1 L_version_cmp "1.1" "==" "1.1a1"
	L_unittest_checkexit 1 L_version_cmp "1.1" "==" "1.1.post1"
	L_unittest_checkexit 1 L_version_cmp "1.1" "==" "1.1.*"
	L_unittest_checkexit 0 L_version_cmp "11" "==" "11"
	L_unittest_checkexit 0 L_version_cmp "systemd-123" "==" "systemd-123"
	L_unittest_checkexit 0 L_version_cmp "bar-123" "<" "foo-123"
	L_unittest_checkexit 0 L_version_cmp "123a" ">" "123"
	L_unittest_checkexit 0 L_version_cmp "123.a" ">" "123"
	L_unittest_checkexit 0 L_version_cmp "123.a" "<" "123.b"
	L_unittest_checkexit 0 L_version_cmp "123a" ">" "123.a"
	L_unittest_checkexit 0 L_version_cmp "11α" "==" "11β"
	L_unittest_checkexit 0 bash -c 'LIB_SCRIPT="$0"; . "$LIB_SCRIPT"; LC_ALL=C; L_version_cmp "B" "<" "a"' "$L_LIB_SCRIPT"
	L_unittest_checkexit 0 L_version_cmp "" "<" "0"
	L_unittest_checkexit 0 L_version_cmp "0." ">" "0"
	L_unittest_checkexit 0 L_version_cmp "0.0" ">" "0"
	L_unittest_checkexit 0 L_version_cmp "0" ">" "~"
	L_unittest_checkexit 0 L_version_cmp "" ">" "~"
	L_unittest_checkexit 0 L_version_cmp "1_" "==" "1"
	L_unittest_checkexit 0 L_version_cmp "_1" "==" "1"
	L_unittest_checkexit 0 L_version_cmp "1_" "<" "1.2"
	L_unittest_checkexit 0 L_version_cmp "1_2_3" ">" "1.3.3"
	L_unittest_checkexit 0 L_version_cmp "1+" "==" "1"
	L_unittest_checkexit 0 L_version_cmp "+1" "==" "1"
	L_unittest_checkexit 0 L_version_cmp "1+" "<" "1.2"
	L_unittest_checkexit 0 L_version_cmp "1+2+3" ">" "1.3.3"
	L_unittest_checkexit 0 L_version_cmp "122.1" "<" "123~rc1-1"
	L_unittest_checkexit 0 L_version_cmp "123~rc1-1" "<" "123"
	L_unittest_checkexit 0 L_version_cmp "123" "<" "123-a"
	L_unittest_checkexit 0 L_version_cmp "123-a" "<" "123-a.1"
	L_unittest_checkexit 0 L_version_cmp "123-a.1" "<" "123-1"
	L_unittest_checkexit 0 L_version_cmp "123-1" "<" "123-1.1"
	L_unittest_checkexit 0 L_version_cmp "123-1.1" "<" "123^post1"
	L_unittest_checkexit 0 L_version_cmp "123^post1" "<" "123.a-1"
	L_unittest_checkexit 0 L_version_cmp "123.a-1" "<" "123.1-1"
	L_unittest_checkexit 0 L_version_cmp "123.1-1" "<" "123a-1"
	L_unittest_checkexit 0 L_version_cmp "123a-1" "<" "124-1"

# Reverse tests
L_unittest_checkexit 0 L_version_cmp "1" ">" "0"
L_unittest_checkexit 0 L_version_cmp "1" ">=" "0"
L_unittest_checkexit 0 L_version_cmp "0.2" ">" "0.1"
L_unittest_checkexit 0 L_version_cmp "10.1.2" ">" "2.3.1"
L_unittest_checkexit 0 L_version_cmp "10.1.2" ">" "1.3.a4"
L_unittest_checkexit 0 L_version_cmp "0.0.2" ">" "0.0.1"
L_unittest_checkexit 0 L_version_cmp "0.0.2" "<" "0.1.0"
L_unittest_checkexit 0 L_version_cmp "0.1.0" "<" "$BASH_VERSION"
L_unittest_checkexit 0 L_version_cmp "1.0.7" ">" "1.0.3"
L_unittest_checkexit 0 L_version_cmp "1.0.7" "<" "1.0.3"
L_unittest_checkexit 0 L_version_cmp "2" "<=" "2.0.1"
L_unittest_checkexit 0 L_version_cmp "2" "<=" "2.1"
L_unittest_checkexit 0 L_version_cmp "2" "<=" "2.0.0"
L_unittest_checkexit 0 L_version_cmp "1.1.0" ">" "1.1"
L_unittest_checkexit 0 L_version_cmp "123" "<" "123a"
L_unittest_checkexit 0 L_version_cmp "123" "<" "123.a"
L_unittest_checkexit 0 L_version_cmp "123.b" ">" "123.a"
L_unittest_checkexit 0 L_version_cmp "123.a" "<" "123a"
L_unittest_checkexit 0 L_version_cmp "11β" "==" "11α"
L_unittest_checkexit 0 L_version_cmp "0" ">" ""
L_unittest_checkexit 0 L_version_cmp "0" "<" "0."
L_unittest_checkexit 0 L_version_cmp "0" "<" "0.0"
L_unittest_checkexit 0 L_version_cmp "~" "<" "0"
L_unittest_checkexit 0 L_version_cmp "~" "<" ""
L_unittest_checkexit 0 L_version_cmp "1.2" ">" "1_"
L_unittest_checkexit 0 L_version_cmp "1.3.3" "<" "1_2_3"
L_unittest_checkexit 0 L_version_cmp "1.2" ">" "1+"
L_unittest_checkexit 0 L_version_cmp "1.3.3" "<" "1+2+3"
	L_unittest_cmd -o "L_lib.sh $L_LIB_VERSION Copyright (C) 2026 Kamil Cukrowski" bash "$L_LIB_SCRIPT" --version
	L_unittest_cmd -o "L_lib.sh $L_LIB_VERSION Copyright (C) 2026 Kamil Cukrowski" bash "$L_LIB_SCRIPT" version
}
