#!/usr/bin/env bash
set -euo pipefail
if [[ "$*" == *" ---- --L_argparse_"* ]]; then
	_time() { "$@"; }
else
	export TIMEFORMAT="real=%lR user=%lU sys=%lS"
	_time() { time "$@"; }
fi
_time . "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/../bin/L_lib.sh
if ((L_HAS_ASSOCIATIVE_ARRAY)); then
	declare -A Adest=()
fi
f() {
	unset SUPER _ FUNCNAME SUPER2
	declare -p | grep -Ev "^declare (-a|-r|-ar|--) (SHELLOPTS|BASH_LINENO|BASH_REMATCH|PIPESTATUS|COLUMNS|LINES)="
}
trap 'L_trap_err $?' EXIT
SUPER=$(f)
if [[ -n "${PROFILE:-}" ]]; then
	echo "SETUPING UP PROFILING..."
	for i in $(compgen -A function L_argparse) $(compgen -A function _L_argparse); do
	  a="$(declare -f $i)"
	  eval "${a/"$i"/_PROFILE_$i}"
	  eval "$i() { local TIMEFORMAT=\"\$((\${BASH_LINENO[@]:+\${#BASH_LINENO[@]}}/2)) $i real=%lR user=%lU sys=%lS\"; time _PROFILE_$i \"\$@\"; }"
	done
	unset i a
fi
_time L_argparse "$@"
# echo $?
diff -biw - <<<"$SUPER" <(f) | sed -n 's/^> /+ /p' || :
