#!/usr/bin/env bash
set -euo pipefail
. "$(dirname "$(readlink -f "$0")")"/../bin/L_lib.sh
if ((L_HAS_ASSOCIATIVE_ARRAY)); then
	declare -A Adest=()
fi
f() {
	unset SUPER _ FUNCNAME SUPER2
	declare -p | grep -Ev "^declare (-a|-r|-ar) (SHELLOPTS|BASH_LINENO|BASH_REMATCH|PIPESTATUS)="
}
trap 'L_trap_err $?' EXIT
SUPER=$(f)
L_argparse "$@"
# echo $?
diff -U0 - <<<"$SUPER" <(f) || :
