---
on:
  - push
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    strategy:
      matrix:
        version:
          - 5.2.13
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          build-args: VERSION=${{ matrix.version }}
          target: test
          cache-from: type=gha
          cache-to: type=gha,mode=max

  pages:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          name: fchastanet/shdoc
          path: shdoc
      - run: mkdir -v ./pages && shdoc/shdoc <./bin/L_lib.sh >./pages/index.md
      - uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: ./pages/index.md
          output: ./pages/index.html
          title: L_lib.sh
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./pages
      - uses: actions/deploy-pages@v4
