---
on:
  - push
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    strategy:
      matrix:
        version:
          - 5.2
          - 4.4
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          build-args: VERSION=${{ matrix.version }}
          target: test
          cache-from: type=gha
          cache-to: type=gha,mode=max

  shellcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          build-args: VERSION=${{ matrix.version }}
          target: shellcheck
          cache-from: type=gha
          cache-to: type=gha,mode=max

  pages:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          name: kamilcuk/shdoc
          path: shdoc
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          build-args: VERSION=${{ matrix.version }}
          target: shellcheck
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=local,dest=pages
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./pages
      - uses: actions/deploy-pages@v4
