name: Release
on: push

jobs:
  test_env_secret:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Verify Token Owner Identity
        run: |
          owner=$(curl -s -H "Authorization: token ${{ secrets.RELEASE_TOKEN }}" https://api.github.com/user | jq -r '.login')
          echo "The token belongs to user: $owner"
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
